import Head from 'next/head'
import Footer from "../components/footer"
import AddFavoriteComponent from "../components/addFavoriteComponent"
import { selectCryptoCoins, selectTotal } from "../slices/basketSlice";
import { useSelector } from "react-redux";
import { useRouter } from 'next/router'


const AddFavoritePage = () => { 

    const totalFavoriteCoin = useSelector(selectCryptoCoins)
    const router = useRouter()


    return (
      <div className="bg-green-100 dark:bg-gray-900 pb-5 h-screen w-screen">
      <Head>
        <title>Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <AddFavoriteComponent />
      <div className="mb-32">
          <h2 className="cursor-pointer text-green-100 font-semibold text-xl mt-10" > .</h2>
      </div>

        <div className="position fixed bottom-16 md:bottom-[14%] w-full text-center p-3 ">
            <button className="bg-green-600 dark:bg-gray-800 py-2 font-bold text-white dark:text-gray-100 text-xl w-[85%] md:w-[60%] rounded-xl" onClick={() => router.push("/favorite")}>{totalFavoriteCoin.length} Coins Added To Favorite</button>
        </div>
        <Footer />
      </div>
    )
  }
  
  export default AddFavoritePage