import Head from "next/head"
import Footer from '../components/footer'
import DiscoverMenu from "../components/discoveringMenu"
import MoreNews from "../components/moreNews"


const LatestNews = () => {

      return (
        <div className="h-screen dark:bg-gray-900 bg-green-100">
            <Head>
            <title>Crypto</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <DiscoverMenu />
            <MoreNews />

            <Footer />

        </div>
  )
};

export default LatestNews;